compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - current
  libc:
    - current
    - musl
  os:
    - linux
    - current

yarnPath: .yarn/releases/yarn-4.0.2.cjs
